# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 14:59
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180811_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u5927\u6570\u636e\u6807\u9898')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='\u5927\u6570\u636e\u6807\u7b7e')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5927\u6570\u636e\u6b63\u6587')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name': '\u5927\u6570\u636e',
                'verbose_name_plural': '\u5927\u6570\u636e',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6e38\u620f\u6807\u9898')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='\u6e38\u620f\u6807\u7b7e')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6e38\u620f\u6b63\u6587')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name': '\u6e38\u620f',
                'verbose_name_plural': '\u6e38\u620f',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u804c\u4e1a\u6807\u9898')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='\u804c\u4e1a\u6807\u7b7e')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u804c\u4e1a\u6b63\u6587')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name': '\u804c\u4e1a',
                'verbose_name_plural': '\u804c\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Python\u6807\u9898')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Python\u6807\u7b7e')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='Python\u6b63\u6587')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name': 'Python',
                'verbose_name_plural': 'Python',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u65c5\u6e38\u6807\u9898')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='\u65c5\u6e38\u6807\u7b7e')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u65c5\u6e38\u6b63\u6587')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name': '\u65c5\u6e38',
                'verbose_name_plural': '\u65c5\u6e38',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': '\u5a31\u4e50', 'verbose_name_plural': '\u5a31\u4e50'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u5a31\u4e50\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5a31\u4e50\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u5a31\u4e50\u6807\u9898'),
        ),
    ]
