# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 14:44
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180815_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u5934\u6761\u6807\u9898')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='\u65c5\u6e38\u6807\u7b7e')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u65c5\u6e38\u6b63\u6587')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name': '\u5934\u6761',
                'verbose_name_plural': '\u5934\u6761',
            },
        ),
    ]
