# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 16:35
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u5934\u6761\u6807\u9898')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u65c5\u6e38\u6b63\u6587')),
            ],
            options={
                'verbose_name': '\u5934\u6761',
                'verbose_name_plural': '\u5934\u6761',
            },
        ),
    ]
